/* Auto-generated by genmsg_java.py for file /Users/kwc/workspace/ros_comm/test/test_ros/msg/TestString.msg */

package org.ros.message.test;

import org.ros.message.Message;

import java.nio.ByteBuffer;

public class TestString extends Message {

  public java.lang.String caller_id = new java.lang.String();
  public java.lang.String orig_caller_id = new java.lang.String();
  public java.lang.String data = new java.lang.String();

  public TestString() {
  }

  public static java.lang.String __s_getDataType() { return "test_ros/TestString"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "334ff4377be93faa44ebc66d23d40fd3"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "# Integration test message\n" +
"# caller_id of most recent node to send this message\n" +
"string caller_id\n" +
"# caller_id of the original node to send this message\n" +
"string orig_caller_id\n" +
"string data\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public TestString clone() {
    TestString c = new TestString();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 4 + caller_id.length();
    __l += 4 + orig_caller_id.length();
    __l += 4 + data.length();
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, caller_id);
    Serialization.writeString(bb, orig_caller_id);
    Serialization.writeString(bb, data);
  }

  public void deserialize(ByteBuffer bb) {
    caller_id = Serialization.readString(bb);
    orig_caller_id = Serialization.readString(bb);
    data = Serialization.readString(bb);
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof TestString))
      return false;
    TestString other = (TestString) o;
    return
      caller_id.equals(other.caller_id) &&
      orig_caller_id.equals(other.orig_caller_id) &&
      data.equals(other.data) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.caller_id == null ? 0 : this.caller_id.hashCode());
    result = prime * result + (this.orig_caller_id == null ? 0 : this.orig_caller_id.hashCode());
    result = prime * result + (this.data == null ? 0 : this.data.hashCode());
    return result;
  }
} // class TestString

