/* Auto-generated by genmsg_java.py for file /usr/local/google/ros/ros_comm/messages/std_msgs/msg/Int64.msg */

package org.ros.message.std;

import org.ros.message.Message;

import java.nio.ByteBuffer;

public class Int64 extends Message {

  public long data;

  public Int64() {
  }

  public static java.lang.String __s_getDataType() { return "std_msgs/Int64"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "34add168574510e6e17f5d23ecc077ef"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "int64 data\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Int64 clone() {
    Int64 c = new Int64();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 8; // data
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    bb.putLong(data);
  }

  public void deserialize(ByteBuffer bb) {
    data = bb.getLong();
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Int64))
      return false;
    Int64 other = (Int64) o;
    return
      data == other.data &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (int)(this.data ^ (this.data >>> 32));
    return result;
  }
} // class Int64

